# generated by datamodel-codegen:
#   filename:  page
#   timestamp: 2020-09-07T14:20:15+00:00

from typing import List, Optional

from pydantic import BaseModel


class NewsAbuItem(BaseModel):
    date: str
    num: int
    subject: str
    views: int


class File(BaseModel):
    displayname: str
    height: int
    install: Optional[str] = None
    name: str
    pack: Optional[str] = None
    path: str
    size: int
    sticker: Optional[str] = None
    thumbnail: str
    tn_height: int
    tn_width: int
    type: int
    width: int
    fullname: Optional[str] = None
    md5: Optional[str] = None
    nsfw: Optional[int] = None
    duration: Optional[str] = None
    duration_secs: Optional[int] = None


class Post(BaseModel):
    banned: int
    closed: int
    comment: str
    date: str
    email: str
    endless: int
    files: List[File]
    files_count: Optional[int] = None
    lasthit: int
    name: str
    num: str
    op: int
    parent: str
    posts_count: Optional[int] = None
    sticky: int
    subject: str
    tags: Optional[str] = None
    timestamp: int
    trip: str


class Thread(BaseModel):
    files_count: int
    posts: List[Post]
    posts_count: int
    thread_num: str


class TopItem(BaseModel):
    board: str
    info: str
    name: str


class Model(BaseModel):
    Board: str
    BoardInfo: str
    BoardInfoOuter: str
    BoardName: str
    advert_bottom_image: str
    advert_bottom_link: str
    advert_mobile_image: str
    advert_mobile_link: str
    advert_top_image: str
    advert_top_link: str
    board_banner_image: str
    board_banner_link: str
    board_speed: int
    bump_limit: int
    current_page: int
    current_thread: int
    default_name: str
    enable_dices: int
    enable_flags: int
    enable_icons: int
    enable_images: int
    enable_likes: int
    enable_names: int
    enable_oekaki: int
    enable_posting: int
    enable_sage: int
    enable_shield: int
    enable_subject: int
    enable_thread_tags: int
    enable_trips: int
    enable_video: int
    is_board: int
    is_index: int
    max_comment: int
    max_files_size: int
    news_abu: List[NewsAbuItem]
    pages: List[int]
    threads: List[Thread]
    top: List[TopItem]
