# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-04-30T21:52:44+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class File(BaseModel):
    duration: Optional[str] = None
    height: int
    md5: str
    name: str
    path: str
    size: int
    thumbnail: str
    tn_height: int
    tn_width: int
    type: int
    width: int
    nsfw: Optional[int] = None


class ModelItem(BaseModel):
    banned: int
    closed: int
    comment: str
    date: str
    email: str
    endless: int
    files: List[File]
    lasthit: int
    name: str
    num: str
    op: int
    parent: str
    sticky: int
    subject: str
    timestamp: int
    trip: str
    trip_type: str
    unique_posters: Optional[str] = None


class Model(BaseModel):
    __root__: List[ModelItem]
