# generated by datamodel-codegen:
#   filename:  post
#   timestamp: 2020-09-07T14:20:17+00:00

from typing import List

from pydantic import BaseModel


class ModelItem(BaseModel):
    banned: int
    closed: int
    comment: str
    date: str
    email: str
    endless: int
    files: List
    lasthit: int
    name: str
    num: str
    op: int
    parent: str
    sticky: int
    subject: str
    timestamp: int
    trip: str
    trip_type: str


class Model(BaseModel):
    __root__: List[ModelItem]
