# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2022-04-30T21:52:43+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Thread(BaseModel):
    comment: str
    lasthit: int
    num: str
    posts_count: int
    score: float
    subject: str
    timestamp: int
    views: int


class Model(BaseModel):
    board: str
    threads: List[Thread]
